const sec1 = "<!DOCTYPE html>\n" +
    "<html lang=\"en\" xmlns=\"http://www.w3.org/1999/xhtml\">\n" +
    "    <head>\n" +
    "        <meta charset=\"utf-8\">\n" +
    "        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n" +
    "        <title>Smart Factory Catalog Information Request</title>\n"

const sec2 = "<style>\n" +
    "        body {\n" +
    "            font-family: Roboto,sans-serif;\n" +
    "            margin: 0 auto !important;\n" +
    "            padding: 0 !important;\n" +
    "            height: 100% !important;\n" +
    "            width: 100% !important;\n" +
    "            background: #f1f1f1;\n" +
    "            font-weight: 400;\n" +
    "            font-size: 15px;\n" +
    "            line-height: 1.8;\n" +
    "            color: rgba(0,0,0,.8);\n" +
    "        }\n" +
    "        * {\n" +
    "            -ms-text-size-adjust: 100%;\n" +
    "            -webkit-text-size-adjust: 100%;\n" +
    "        }\n" +
    "        table,\n" +
    "        td {\n" +
    "            mso-table-lspace: 0pt !important;\n" +
    "            mso-table-rspace: 0pt !important;\n" +
    "        }\n" +
    "        h1,h2,h3,h4,h5,h6{\n" +
    "            color: #000000;\n" +
    "            margin-top: 0;\n" +
    "        }\n" +
    "\n" +
    "    </style>\n"

const sec3 = "<body style=\"margin: 0; padding: 0 !important; mso-line-height-rule: exactly; background-color: #222222;\">\n" +
    "        <div style=\"width: 100%; background-color: #f1f1f1;\">\n" +
    "            <div style=\"max-width: 600px; margin: 0 auto;\" class=\"email-container\">\n" +
    "                <table style=\"margin: auto; width: 100%\">\n" +
    "                    <tr>\n" +
    "                        <td style=\"padding: 1em 2.5em; text-align: center; background: #ffffff;\">\n" +
    "                            <h1>Smart Factory Catalog</h1>\n" +
    "                        </td>\n" +
    "                    </tr>\n" +
    "                    <tr>\n" +
    "                        <td style=\"background-size: cover; height: 400px;\">\n" +
    "                            <div style=\"padding: 0 3em; text-align: center;\">\n" +
    "                                <h2>"

const sec4 = " Requested Information</h2>\n" +
    "                                <p>"

const sec5 = " has requested information regarding the following Smart Factory Catalog Items:</p>\n"

const sec6 = "</div>\n" +
    "                        </td>\n" +
    "                    </tr>\n" +
    "                </table>\n" +
    "                <table style=\"margin: auto; width: 100%\">\n" +
    "                    <tr>\n" +
    "                        <td style=\"background: #000000; color: rgba(255,255,255,.5); padding:1.5em;\">\n" +
    "                            <p>This email was generated by Nifco Smart Factory Catalog</p>\n" +
    "                        </td>\n" +
    "                    </tr>\n" +
    "                </table>\n" +
    "            </div>\n" +
    "        </div>\n" +
    "    </body>\n" +
    "</html>"

export function createEmailBody(name, cartItems) {
    let beforeArray = sec1 + sec2 + sec3 + name + sec4 + name.split(' ')[0] + sec5

    let cartArray = ""
    cartItems.forEach(x =>
        cartArray = cartArray + "<p>" + x + "</p>\n"
    )

    return beforeArray + cartArray + sec6
}