import {v4 as uuidv4} from "uuid";
import materialPurchasingTool from '../../images/materialPurchasingTool.png'
import planningSchedulingJobs from '../../images/planningSchedulingJobs.png'
import materialIssuing from '../../images/materialIssuing.png'
import mesDash from '../../images/mesDash.png'
import pup from '../../images/pup.png'
import mesAssmbly from '../../images/mesAssembly.png'
import wow from '../../images/wow.png'
import notify from '../../images/notify.png'
import tableau from '../../images/tableau.png'
import spc from '../../images/spc.png'
import autoLabel from '../../images/autoLabel.png'
import {atom} from "recoil";

const list = [
    {
        longTitle: 'Material Purchasing Interface',
        shortTitle: 'Purchasing',
        status: 'released',
        imgURL: materialPurchasingTool,
        link: 'https://purchasing.nifconet.com/',
        description: 'Shows all upcoming transactions including part orders, forecasts, and planned jobs in one place',
        details: 'Links to all part numbers produced with each raw material with each org. ' +
            'Shows go-short date and order by date (by lead times). ' +
            'Shows any materials projected to go short based on upcoming production schedule',
        unitAdoption: ['U1','U20'],
        department: 'Production',
        org: 'CNL',
    },
    {
        longTitle: 'Scheduling Interfaces for Molding',
        shortTitle: 'Planning and Scheduling Jobs',
        status: 'in progress',
        imgURL: planningSchedulingJobs,
        link: 'https://planning.nifconet.com/',
        description: 'Job planning, and mold change screen + app',
        details: 'Shows all upcoming transactions including orders, forecasts and planned jobs in one place. ' +
            'Displays jobs proposed by ASCP, and allows them to be released without going into Oracle. ' +
            'Shows on hand quantities, materials needed, part routings, etc',
        unitAdoption: ['U1','U20'],
        department: 'Production',
        org: 'CNL',
    },
    {
        longTitle: 'Planning Interface for Molding',
        shortTitle: 'Planning Jobs',
        status: 'in progress',
        imgURL: planningSchedulingJobs,
        link: 'https://scheduling.nifconet.com/',
        description: 'Job scheduling, and mold change screen + app',
        details: 'Shows all upcoming transactions including orders, forecasts and planned jobs in one place. ' +
            'Displays jobs proposed by ASCP, and allows them to be released without going into Oracle. ' +
            'Shows on hand quantities, materials needed, part routings, etc',
        unitAdoption: ['U1','U20'],
        department: 'Production',
        org: 'CNL',
    },
    {
        longTitle: 'Material Issuing Process',
        shortTitle: 'Material Issuing',
        status: 'released',
        imgURL: materialIssuing,
        link: null,
        description: 'Allows molding material handlers to view pending material requests and issue material',
        details: 'This updates the inventory quantities, as well as maintains lot traceability within Oracle. ' +
            'The app is tied to smart scales to ensure weight being issued is accurate.',
        unitAdoption: ['U1','U20'],
        department: 'Production',
        org: 'CNL',
    },
    {
        longTitle: 'Press Status Monitoring and Data Collection',
        shortTitle: 'MES Dashboard',
        status: 'released',
        imgURL: mesDash,
        link: 'https://d2oahh0q3kzduj.cloudfront.net/',
        description: 'Allows production to monitor press status and details real-time',
        details: '',
        unitAdoption: ['U1','U20'],
        department: 'Production',
        org: 'CNL',
    },
    {
        longTitle: 'Press Downtime Monitoring and Reason Tracking',
        shortTitle: 'PUP',
        status: 'released',
        imgURL: pup,
        link: 'https://pup.nifconet.com/',
        description: 'Helps production team monitor down presses and assign reasons',
        details: '',
        unitAdoption: ['U1','U20'],
        department: 'Production',
        org: 'CNL',
    },
    {
        longTitle: 'MES for Assembly',
        shortTitle: 'MES Dashboard',
        status: 'released',
        imgURL: mesAssmbly,
        link: null,
        description: 'The Run/Pause button on the HMI indicates to PUP if a machine is running or down',
        details: 'This button is only active if the machine has a “heartbeat.” ' +
            'A heartbeat requires the machine to be connected to the network, a job to be scanned in, and the selected part to match the job.',
        unitAdoption: ['U1','U20'],
        department: 'Production',
        org: 'CNL',
    },
    {
        longTitle: 'Nifco WOW (iPhone)',
        shortTitle: 'iPhone Apps',
        status: 'released',
        imgURL: wow,
        link: null,
        description: 'iPhone Apps allow the Production team to have an easily accessible system to ensure data is collected properly within the MES system.',
        details: 'There are many MES apps.',
        unitAdoption: ['U1','U20'],
        department: 'Production',
        org: 'CNL',
    },
    {
        longTitle: 'Notification Manager (iPhone)',
        shortTitle: 'iPhone Apps',
        status: 'released',
        imgURL: notify,
        link: null,
        description: '',
        details: '',
        unitAdoption: ['U1','U20'],
        department: 'Production',
        org: 'CNL',
    },
    {
        longTitle: 'Tableau Data Monitoring',
        shortTitle: 'Tableau',
        status: 'released',
        imgURL: tableau,
        link: 'http://ec2-54-149-155-132.us-west-2.compute.amazonaws.com/#/projects/1',
        description: 'Gives management the ability to analyze the major contributors to low OEE',
        details: 'Operation rate/availability % (unplanned downtime). Performance Efficiency % (cycle time/cavitation issues). Quality Rate % (in-process defects)',
        unitAdoption: ['U1','U20'],
        department: 'Production',
        org: 'CNL',
    },
    {
        longTitle: 'Part Quality Monitoring (iPhone)',
        shortTitle: 'SPC Manager',
        status: 'released',
        imgURL: spc,
        link: 'https://spc.nifconet.com/',
        description: 'Statistical process control manager. Allows quality group to record and monitor in-process checks',
        details: 'Data is recorded for historical purposes – good for root cause analysis. ' +
            'Data can be reviewed for trends. ' +
            'Quality and Production personnel can be alerted when a part is out of spec.',
        unitAdoption: ['U1','U20'],
        department: 'Production',
        org: 'CNL',
    },
    {
        longTitle: 'Auto Labeling Capabilities',
        shortTitle: 'Labels',
        status: 'released',
        imgURL: autoLabel,
        link: null,
        description: 'This system automatically prints labels based on production counts from MES so Operators do not have to manually print labels',
        details: 'The Auto-labeling app can be used to toggle between primary and alternate packaging methods. ' +
            'This will update the labels to show the correct quantity and container number.',
        unitAdoption: ['U1','U20'],
        department: 'Production',
        org: 'CNL',
    },
    {
        longTitle: 'Line Side Labeling with Quantity Verification',
        shortTitle: 'LSL',
        status: 'released',
        imgURL: '',
        link: null,
        description: '',
        details: '',
        unitAdoption: [],
        department: 'Production',
        org: 'SLB',
    },
    {
        longTitle: 'Master Setup Verification',
        shortTitle: 'MSV',
        status: 'released',
        imgURL: '',
        link: 'https://msv.nifconet.com/',
        description: 'Allows engineering to save process parameters',
        details: 'Provides a means for continuous monitoring of process parameters. ' +
            'Allows for easy and more frequent process audits. ' +
            'Utilizes alert screens and Notification Manager to prompt immediate action',
        unitAdoption: ['U1','U20'],
        department: 'Production',
        org: 'SLB',
    },
    {
        longTitle: 'Part Photo Manager',
        shortTitle: 'Photos',
        status: 'released',
        imgURL: '',
        link: 'https://photomanager.nifconet.com/',
        description: '',
        details: '',
        unitAdoption: ['U1','U20'],
        department: 'Production',
        org: 'LVG',
    },
    {
        longTitle: 'Pack Station Process',
        shortTitle: 'Packing',
        status: 'released',
        imgURL: '',
        link: null,
        description: '',
        details: '',
        unitAdoption: ['U1','U20'],
        department: 'Production',
        org: 'LVG',
    },
    {
        longTitle: 'Production Engineering Assembly Asset Management Tool',
        shortTitle: 'Assets',
        status: 'released',
        imgURL: '',
        link: 'https://prodeng.nifconet.com/',
        description: '',
        details: '',
        unitAdoption: ['U1','U20'],
        department: 'Design',
        org: 'CNL',
    },
    {
        longTitle: 'Driver Kiosk Sign in and Trip Management',
        shortTitle: 'Shipping',
        status: 'released',
        imgURL: '',
        link: 'https://trips.nifconet.com/',
        description: '',
        details: '',
        unitAdoption: ['U1','U20'],
        department: 'Quality',
        org: 'CNL',
    },
    {
        longTitle: 'Toyota Skid Build',
        shortTitle: 'SLB',
        status: 'released',
        imgURL: '',
        link: null,
        description: '',
        details: '',
        unitAdoption: ['U1','U20'],
        department: 'Packaging',
        org: 'CNL',
    },
    {
        longTitle: 'Work Order Based Time Tracker',
        shortTitle: 'Time Tracker',
        status: 'released',
        imgURL: '',
        link: 'https://time.nifconet.com/',
        description: '',
        details: '',
        unitAdoption: ['U1','U20'],
        department: 'Design',
        org: 'CNL',
    },
    {
        longTitle: 'Clean-point Checklist',
        shortTitle: 'Checklist',
        status: 'released',
        imgURL: '',
        link: 'https://checklist.nifconet.com/',
        description: '',
        details: '',
        unitAdoption: ['U1','U20'],
        department: 'Quality',
        org: 'CNL',
    },
    {
        longTitle: 'Staffing Management',
        shortTitle: 'Staffing',
        status: 'released',
        imgURL: '',
        link: 'https://staffing.nifconet.com/',
        description: '',
        details: '',
        unitAdoption: ['U1','U20'],
        department: 'Production',
        org: 'CNL',
    }
]

export const sfCatalogList = list.map(x => ({...x, recordId: uuidv4()}))

export const catalogListAtom = atom({
    key: "catalogListAtom",
    default: sfCatalogList,
});

export const filteredCatalog = atom({
    key: "filteredCatalog",
    default: catalogListAtom,
});